---
name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    runs-on: macos-14
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Prepare build environment
        run: |
          pip install wheel>=0.40.0 twine numpy setuptools
      - name: Build wheel
        run: |
          curl -J -O -L 'https://pypi.io/packages/source/z/zeroc-ice/zeroc-ice-3.6.5.tar.gz'
          tar zxf zeroc-ice-3.6.5.tar.gz
          patch -p0 < zeroc-ice-feedstock/recipe/osx.patch
          for f in patches/*; do patch -p0 < ${f}; done
          cd zeroc-ice-3.6.5
          export ARCHFLAGS="-arch arm64 -arch x86_64"
          export CXXFLAGS="-Wno-error=deprecated-declarations"
          export CFLAGS="-Wno-error=implicit-function-declaration"
          export CXXARCHFLAGS="-arch arm64 -arch x86_64"
          export MACOSX_DEPLOYMENT_TARGET=11.0
          python setup.py build -j 6
          python setup.py bdist_wheel
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: zeroc-ice-3.6.5/dist/*.whl
          if-no-files-found: error
  release:
    if: startsWith(github.ref, 'refs/tags')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts from build
        uses: actions/download-artifact@v3
      - name: List artifacts
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*.whl
